### ISSUE TITLE
Automated updates failing

### ISSUE THREAD

**Issue by infinisil** [DeterminateSystems/.github#5]
Your GitHub action to update the relative blog post dates on https://github.com/DeterminateSystems/ is failing since like 2023-12-13: https://github.com/DeterminateSystems/.github/actions/runs/7199230602/job/19610456171

```
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: Review all repository rules at http://github.com/DeterminateSystems/.github/rules?ref=refs%2Fheads%2Fmain        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
```

Looks like you might not want to enable branch protection here, or alternatively make CI open PRs, or perhaps best, not using relative dates :)

This leads to misleading blog post times:

> We regularly write about what we're working on; here are some recent blog posts:
> - [KVM on GitHub Actions](https://determinate.systems/posts/kvm-on-github-actions) (1 week ago)

Ping @cole-h @flexiondotorg

**Comment by cole-h** [comment]
...oops, indeed. It should be fixed now.

Thanks for noticing and opening an issue!
